name: Run SauceDemo Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      URLS_BASE: ${{ vars.URLS_BASE }}
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ vars.PASSWORD }}
      FIRST_NAME: ${{ vars.FIRST_NAME }}
      LAST_NAME: ${{ vars.LAST_NAME }}
      POSTAL_CODE: ${{ vars.POSTAL_CODE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
